export const ADMIN_REQUEST = "ADMIN_REQUEST";
export const ADMIN_GET_REQUEST = "ADMIN_GET_REQUEST";
export const ADMIN_POST_REQUEST = "ADMIN_POST_REQUEST";
export const ADMIN_PATCH_REQUEST = "ADMIN_PATCH_REQUEST";
export const ADMIN_DELETE_REQUEST = "ADMIN_DELETE_REQUEST";
export const ADMIN_FAILURE_REQUEST = "ADMIN_FAILURE_REQUEST";